// Generated by CoffeeScript 1.3.1
(function() {

  define("kopi/utils/i18n/messages/zh_CN", function(require, exports, module) {
    var i18n;
    i18n = require("kopi/utils/i18n");
    return i18n.define("zh_CN", {
      hello: "你好！",
      loading: "正在载入..."
    });
  });

}).call(this);
