// Generated by CoffeeScript 1.3.3
(function() {
  var __slice = [].slice;

  define("kopi/settings", function(require, exports, module) {
    var $, commit, exceptions, kopi, load;
    $ = require("jquery");
    exceptions = require("kopi/exceptions");
    kopi = {
      debug: true,
      app: {
        task: false,
        startURL: null,
        usePushState: true,
        useHashChange: true,
        useInterval: true,
        interval: 50,
        alwaysUseHash: true,
        redirectWhenNoRouteFound: false
      },
      i18n: {
        locale: "en",
        fallback: "en"
      },
      logging: {
        level: 0,
        console: true
      },
      ui: {
        prefix: "kopi",
        notification: {
          prefix: "kopi-notification"
        },
        imageDir: "/images"
      },
      db: {
        indexedDB: {
          name: "kopi_db"
        }
      },
      tracking: {
        account: null,
        domain: location.host
      }
    };
    load = function() {
      throw new exceptions.NotImplementedError();
    };
    commit = function() {
      throw new exceptions.NotImplementedError();
    };
    return {
      kopi: kopi,
      load: load,
      commit: commit,
      extend: function() {
        return $.extend.apply($, [true, exports].concat(__slice.call(arguments)));
      }
    };
  });

}).call(this);
