// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  define("kopi/views", function(require, exports, module) {
    var View, events, exceptions, func, html, klass, logger, logging, settings, text, utils;
    exceptions = require("kopi/exceptions");
    klass = require("kopi/utils/klass");
    settings = require("kopi/settings");
    events = require("kopi/events");
    logging = require("kopi/logging");
    utils = require("kopi/utils");
    html = require("kopi/utils/html");
    text = require("kopi/utils/text");
    func = require("kopi/utils/func");
    logger = logging.logger(module.id);
    /*
      Base class of views
    
      Life cycle of a view:
    
      Constructor -> Create -> Start (-> Update) -> Stop -> Destroy (-> Create -> ...)
    
    
      Example:
    
        class SomeView
    
          oncreate: ->
            this.nav = new SomeNav()
            this.content = new SomeContent()
            this.footer = new SomeTabs()
    
          onstart: ->
            this.nav.skeleton().render()
            this.content.skeleton().render()
            this.footer.skeleton().render()
    
            this.app.navBar.load(this.nav)
            this.app.viewFlipper.load(this.content)
            this.app.tabBar.load(this.footer)
    
          onstop: ->
            this.nav.destroy()
            this.content.destroy()
            this.footer.destroy()
    
          ondestroy: ->
            this.nav = null
            this.content = null
            this.footer = null
    */

    View = (function(_super) {
      var kls;

      __extends(View, _super);

      kls = View;

      kls.CREATE_EVENT = "create";

      kls.CREATED_EVENT = "created";

      kls.START_EVENT = "start";

      kls.STARTED_EVENT = "started";

      kls.UPDATE_EVENT = "update";

      kls.UPDATED_EVENT = "updated";

      kls.STOP_EVENT = "stop";

      kls.STOPPED_EVENT = "stopped";

      kls.DESTROY_EVENT = "destroy";

      kls.DESTROYED_EVENT = "destroyed";

      kls.LOCK_EVENT = "lock";

      kls.UNLOCK_EVENT = "unlock";

      klass.accessor(kls, "viewName", {
        get: function() {
          return this._viewName || (this._viewName = this.name);
        }
      });

      View.viewName("View");

      function View(app, url, params) {
        var self, _base;
        if (params == null) {
          params = {};
        }
        if (!app) {
          throw new exceptions.ValueError("app must be instance of Application");
        }
        self = this;
        (_base = self.constructor).prefix || (_base.prefix = text.dasherize(self.constructor.viewName()));
        self.guid = utils.guid(self.constructor.prefix);
        self.app = app;
        self.url = url;
        self.params = params;
        self.created = false;
        self.started = false;
        self.locked = false;
      }

      /*
          Initialize UI components skeleton and append them to DOM Tree
      */


      View.prototype.create = function(options, fn) {
        var cls, self;
        cls = this.constructor;
        self = this;
        if (self.created || self.locked) {
          logger.warn("View is already created or locked.");
          if (fn) {
            fn("View is already created or locked.", self);
          }
          return self;
        }
        if (!fn && func.isFunction(options)) {
          fn = options;
          options = {};
        }
        logger.info("Create view. " + self.guid);
        self.lock();
        if (fn) {
          self.on(cls.CREATED_EVENT, function(e, error) {
            return fn(error, self);
          });
        }
        return self.emit(cls.CREATE_EVENT, [options]);
      };

      /*
          Display UI components and then render them with data
      */


      View.prototype.start = function(url, params, options, fn) {
        var cls, self;
        cls = this.constructor;
        self = this;
        if (!self.created) {
          throw new exceptions.ValueError("Must create view first.");
        }
        if (self.started || self.locked) {
          logger.warn("View is already started or locked.");
          if (fn) {
            fn("View is already started or locked.", self);
          }
          return self;
        }
        if (!fn && func.isFunction(options)) {
          fn = options;
          options = {};
        }
        logger.info("Start view. " + self.guid);
        self.lock();
        if (fn) {
          self.on(cls.STARTED_EVENT, function(e, error) {
            return fn(error, self);
          });
        }
        return self.emit(cls.START_EVENT, [url, params, options]);
      };

      /*
          Update UI components when URL changes
      */


      View.prototype.update = function(url, params, options, fn) {
        var cls, self;
        cls = this.constructor;
        self = this;
        if (!self.started) {
          throw new exceptions.ValueError("Must start view first.");
          if (fn) {
            fn("Must start view first.", self);
          }
        }
        if (self.locked) {
          logger.warn("View is locked.");
          if (fn) {
            fn("View is locked.", self);
          }
          return self;
        }
        if (!fn && func.isFunction(options)) {
          fn = options;
          options = {};
        }
        logger.info("Update view. " + self.guid);
        if (fn) {
          self.on(cls.UPDATED_EVENT, function(e, error) {
            return fn(error, this);
          });
        }
        return self.emit(cls.UPDATE_EVENT, [url, params, options]);
      };

      /*
          Hide UI components
      */


      View.prototype.stop = function(options, fn) {
        var cls, self;
        cls = this.constructor;
        self = this;
        if (!self.created) {
          throw new exceptions.ValueError("Must create view first.");
        }
        if (!self.started || self.locked) {
          logger.warn("View is already stopped or locked.");
          if (fn) {
            fn("View is already stopped or locked.", self);
          }
          return self;
        }
        if (!fn && func.isFunction(options)) {
          fn = options;
          options = {};
        }
        logger.info("Stop view. " + self.guid);
        self.lock();
        if (fn) {
          self.on(cls.STOPPED_EVENT, function(e, error) {
            return fn(error, self);
          });
        }
        return self.emit(cls.STOP_EVENT, [options]);
      };

      /*
          Remove UI components from DOM Tree
      */


      View.prototype.destroy = function(options, fn) {
        var cls, self;
        cls = this.constructor;
        self = this;
        if (self.started) {
          throw new exceptions.ValueError("Must stop view first.");
        }
        if (!self.created || self.locked) {
          logger.warn("View is already destroyed or locked.");
          if (fn) {
            fn("View is already destroyed or locked.", self);
          }
          return self;
        }
        if (!fn && func.isFunction(options)) {
          fn = options;
          options = {};
        }
        logger.info("Destroy view. " + self.guid);
        self.lock();
        if (fn) {
          self.on(cls.DESTROYED_EVENT, function(e, error) {
            return fn(error, self);
          });
        }
        return self.emit(cls.DESTROY_EVENT, [options]);
      };

      View.prototype.lock = function(fn) {
        var cls, self;
        cls = this.constructor;
        self = this;
        if (self.locked) {
          return self;
        }
        logger.info("Lock view. " + self.guid);
        self.locked = true;
        self.emit(cls.LOCK_EVENT);
        if (fn) {
          fn(null, self);
        }
        return self;
      };

      View.prototype.unlock = function(fn) {
        var cls, self;
        cls = this.constructor;
        self = this;
        if (!self.locked) {
          return self;
        }
        logger.info("Unlock view. " + self.guid);
        self.locked = false;
        self.emit(cls.UNLOCK_EVENT);
        if (fn) {
          fn(null, self);
        }
        return self;
      };

      /*
          Template methods of view events
      */


      View.prototype.oncreate = function(e) {
        var cls, self;
        cls = this.constructor;
        self = this;
        self.created = true;
        self.unlock();
        logger.info("View created. " + self.guid);
        return self.emit(cls.CREATED_EVENT);
      };

      View.prototype.onstart = function(e) {
        var cls, self;
        cls = this.constructor;
        self = this;
        self.started = true;
        self.unlock();
        logger.info("View started. " + self.guid);
        return self.emit(cls.STARTED_EVENT);
      };

      View.prototype.onupdate = function(e) {
        var cls, self;
        cls = this.constructor;
        self = this;
        logger.info("View updated. " + self.guid);
        return self.emit(cls.UPDATED_EVENT);
      };

      View.prototype.onstop = function(e) {
        var cls, self;
        cls = this.constructor;
        self = this;
        self.started = false;
        self.unlock();
        logger.info("View stopped. " + self.guid);
        return self.emit(cls.STOPPED_EVENT);
      };

      View.prototype.ondestroy = function(e) {
        var cls, self;
        cls = this.constructor;
        self = this;
        self.created = false;
        self.unlock();
        logger.info("View destroyed. " + self.guid);
        return self.emit(cls.DESTROYED_EVENT);
      };

      View.prototype.onlock = function(e) {};

      View.prototype.onunlock = function(e) {};

      /*
          Helper methods
      */


      View.prototype.equals = function(view) {
        return this.guid === view.guid;
      };

      return View;

    })(events.EventEmitter);
    return {
      View: View
    };
  });

}).call(this);
