// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  define("kopi/db/adapters/android", function(require, exports, module) {
    var AndroidSQLAdapter, sql;
    sql = require("kopi/db/adapters/sql");
    AndroidSQLAdapter = (function(_super) {

      __extends(AndroidSQLAdapter, _super);

      AndroidSQLAdapter.name = 'AndroidSQLAdapter';

      function AndroidSQLAdapter() {
        return AndroidSQLAdapter.__super__.constructor.apply(this, arguments);
      }

      return AndroidSQLAdapter;

    })(sql.SQLAdapter);
    return {
      AndroidSQLAdapter: AndroidSQLAdapter
    };
  });

}).call(this);
