// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  define("kopi/db/adapters/websql", function(require, exports, module) {
    var WebSQLAdapter, sql, support;
    support = require("kopi/utils/support");
    sql = require("kopi/db/adapters/sql");
    WebSQLAdapter = (function(_super) {

      __extends(WebSQLAdapter, _super);

      WebSQLAdapter.name = 'WebSQLAdapter';

      function WebSQLAdapter() {
        return WebSQLAdapter.__super__.constructor.apply(this, arguments);
      }

      WebSQLAdapter.support = function() {
        return support.websql;
      };

      return WebSQLAdapter;

    })(sql.SQLAdapter);
    return {
      WebSQLAdapter: WebSQLAdapter
    };
  });

}).call(this);
