// Generated by CoffeeScript 1.3.1
(function() {

  define("kopi/ui/pagination", function(require, exports, module) {
    var widgets;
    return widgets = require("kopi/ui/widgets");
  });

}).call(this);
