// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  define("kopi/ui/pinchable", function(require, exports, module) {
    var Pinchable, touchable;
    touchable = require("kopi/ui/touchable");
    Pinchable = (function(_super) {

      __extends(Pinchable, _super);

      Pinchable.name = 'Pinchable';

      function Pinchable() {
        return Pinchable.__super__.constructor.apply(this, arguments);
      }

      return Pinchable;

    })(touchable.Touchable);
    return {
      Pinchable: Pinchable
    };
  });

}).call(this);
