// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  define("kopi/clients/android", function(require, exports, module) {
    var AndroidClient, base, clients;
    base = require("kopi/clients/base");
    clients = require("kopi/clients");
    AndroidClient = (function(_super) {

      __extends(AndroidClient, _super);

      AndroidClient.name = 'AndroidClient';

      function AndroidClient() {
        return AndroidClient.__super__.constructor.apply(this, arguments);
      }

      return AndroidClient;

    })(base.BaseClient);
    clients.register("android", AndroidClient);
    return {
      AndroidClient: AndroidClient
    };
  });

}).call(this);
