// Generated by CoffeeScript 1.3.1
(function() {

  define("kopi/clients/base", function(require, exports, module) {
    var BaseClient, clients;
    clients = require("kopi/clients");
    BaseClient = (function() {

      BaseClient.name = 'BaseClient';

      function BaseClient() {}

      return BaseClient;

    })();
    return {
      BaseClient: BaseClient
    };
  });

}).call(this);
