// Generated by CoffeeScript 1.3.1
(function() {

  define("kopi/utils/http", function(require, exports, module) {
    var $, logger, logging, request;
    $ = require("jquery");
    logging = require("kopi/logging");
    logger = logging.logger(module.id);
    /*
      Provide some high-level wrappers around $.ajax
    
      TODO Retry when error happens
      TODO Add Delayed requests to task queue
    */

    request = function(options) {
      return $.ajax(options);
    };
    return {
      request: request
    };
  });

}).call(this);
