// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  define("kopi/clients/ios", function(require, exports, module) {
    var IOSClient, base, clients;
    base = require("kopi/clients/base");
    clients = require("kopi/clients");
    IOSClient = (function(_super) {

      __extends(IOSClient, _super);

      IOSClient.name = 'IOSClient';

      function IOSClient() {
        return IOSClient.__super__.constructor.apply(this, arguments);
      }

      return IOSClient;

    })(base.BaseClient);
    clients.register("ios", IOSClient);
    return {
      IOSClient: IOSClient
    };
  });

}).call(this);
