// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  define("kopi/clients/windowsphone", function(require, exports, module) {
    var WindowsPhoneClient, base, clients;
    base = require("kopi/clients/base");
    clients = require("kopi/clients");
    WindowsPhoneClient = (function(_super) {

      __extends(WindowsPhoneClient, _super);

      WindowsPhoneClient.name = 'WindowsPhoneClient';

      function WindowsPhoneClient() {
        return WindowsPhoneClient.__super__.constructor.apply(this, arguments);
      }

      return WindowsPhoneClient;

    })(base.BaseClient);
    clients.register("windowsphone", WindowsPhoneClient);
    return {
      WindowsPhoneClient: WindowsPhoneClient
    };
  });

}).call(this);
