// Generated by CoffeeScript 1.3.1
(function() {

  define("main", function(require, exports, module) {
    var DocApp, notification;
    notification = require("kopi/ui/notification");
    DocApp = require("doc/app").DocApp;
    notification.loading();
    new DocApp().start();
  });

}).call(this);
