// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  define("kopi/ui/lists/paginations", function(require, exports, module) {
    var ListPagination, items;
    items = require("kopi/ui/lists/items");
    ListPagination = (function(_super) {

      __extends(ListPagination, _super);

      ListPagination.name = 'ListPagination';

      function ListPagination() {
        return ListPagination.__super__.constructor.apply(this, arguments);
      }

      return ListPagination;

    })(items.ListItem);
    return {
      ListPagination: ListPagination
    };
  });

}).call(this);
