// Generated by CoffeeScript 1.3.1
(function() {

  define("kopi/tests/ui/text", function(require, exports, module) {
    var $, LONG_TEXT, SHORT_TEXT, text;
    $ = require("jquery");
    text = require("kopi/ui/text");
    SHORT_TEXT = "The Zen of Python, by Tim Peters";
    LONG_TEXT = "Beautiful is better than ugly.\nExplicit is better than implicit.\nSimple is better than complex.\nComplex is better than complicated.\nFlat is better than nested.\nSparse is better than dense.\nReadability counts.\nSpecial cases aren't special enough to break the rules.\nAlthough practicality beats purity.\nErrors should never pass silently.\nUnless explicitly silenced.\nIn the face of ambiguity, refuse the temptation to guess.\nThere should be one-- and preferably only one --obvious way to do it.\nAlthough that way may not be obvious at first unless you're Dutch.\nNow is better than never.\nAlthough never is often better than *right* now.\nIf the implementation is hard to explain, it's a bad idea.\nIf the implementation is easy to explain, it may be a good idea.\nNamespaces are one honking great idea -- let's do more of those!";
    return $(function() {
      q.module("kopi.ui.text");
      q.test("ellipsis short text", function() {
        var ellipsisText;
        ellipsisText = new text.EllipsisText("#ellipsis-short-text");
        ellipsisText.text(SHORT_TEXT);
        ellipsisText.skeleton();
        return ellipsisText.render();
      });
      return q.test("ellipsis long text", function() {
        var ellipsisText;
        ellipsisText = new text.EllipsisText("#ellipsis-long-text");
        ellipsisText.text(LONG_TEXT);
        ellipsisText.skeleton();
        return ellipsisText.render();
      });
    });
  });

}).call(this);
