// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define("kopi/tests/ui/touchable", function(require, exports, module) {
    var $, CustomGesture, PhotoGallery, Touchable, g;
    $ = require("jquery");
    Touchable = require("kopi/ui/touchable").Touchable;
    g = require("kopi/ui/gestures");
    CustomGesture = (function(_super) {

      __extends(CustomGesture, _super);

      CustomGesture.configure({
        preventDefault: true
      });

      function CustomGesture() {
        CustomGesture.__super__.constructor.apply(this, arguments);
        this._previousTaps = [];
      }

      CustomGesture.prototype.ontouchstart = function(e) {
        return this.reset();
      };

      CustomGesture.prototype.ontouchmove = function(e) {};

      CustomGesture.prototype.ontouchend = function(e) {};

      CustomGesture.prototype.ontouchcancel = function(e) {
        return this.touchend(e);
      };

      CustomGesture.prototype.reset = function() {};

      return CustomGesture;

    })(g.Base);
    PhotoGallery = (function(_super) {

      __extends(PhotoGallery, _super);

      function PhotoGallery() {
        return PhotoGallery.__super__.constructor.apply(this, arguments);
      }

      PhotoGallery.widgetName("PhotoGallery");

      PhotoGallery.configure({
        gestures: [CustomGesture]
      });

      PhotoGallery.prototype.onskeleton = function() {};

      PhotoGallery.prototype.onrender = function() {};

      return PhotoGallery;

    })(Touchable);
    return $(function() {
      return new PhotoGallery().skeleton("#container").render();
    });
  });

}).call(this);
