// Generated by CoffeeScript 1.3.1
(function() {

  define("kopi/ie", function() {
    var doc;
    doc = document;
    doc.createElement('header');
    doc.createElement('hgroup');
    doc.createElement('nav');
    doc.createElement('menu');
    doc.createElement('section');
    doc.createElement('article');
    doc.createElement('aside');
    doc.createElement('footer');
    doc.createElement('figure');
    doc.createElement('figurecaption');
  });

}).call(this);
