// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  define("kopi/ui/droppable", function(require, exports, module) {
    var Droppable, touchable;
    touchable = require("kopi/ui/touchable");
    /*
      A widget can be dragged by mouse or finger
    */

    Droppable = (function(_super) {

      __extends(Droppable, _super);

      Droppable.name = 'Droppable';

      function Droppable() {
        return Droppable.__super__.constructor.apply(this, arguments);
      }

      return Droppable;

    })(touchable.Touchable);
    return {
      Droppable: Droppable
    };
  });

}).call(this);
