// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  define("kopi/ui/startup", function(require, exports, module) {
    var $, SplashScreen, widgets;
    $ = require("jquery");
    widgets = require("kopi/ui/widgets");
    SplashScreen = (function(_super) {

      __extends(SplashScreen, _super);

      SplashScreen.name = 'SplashScreen';

      function SplashScreen() {
        return SplashScreen.__super__.constructor.apply(this, arguments);
      }

      SplashScreen.prototype.onskeleton = function() {
        $(this.element).bind("click", function(e) {
          return false;
        });
        return SplashScreen.__super__.onskeleton.apply(this, arguments);
      };

      return SplashScreen;

    })(widgets.Widget);
    return {
      SplashScreen: SplashScreen
    };
  });

}).call(this);
