// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  define("kopi/ui/touchable", function(require, exports, module) {
    var $, Touchable, doc, events, support, widgets;
    $ = require("jquery");
    events = require("kopi/utils/events");
    support = require("kopi/utils/support");
    widgets = require("kopi/ui/widgets");
    doc = $(document);
    /*
      A widget supports touch events
    */

    Touchable = (function(_super) {
      var kls;

      __extends(Touchable, _super);

      kls = Touchable;

      kls.TOUCH_START_EVENT = "touchstart";

      kls.TOUCH_MOVE_EVENT = "touchmove";

      kls.TOUCH_END_EVENT = "touchend";

      kls.TOUCH_CANCEL_EVENT = "touchcancel";

      kls.EVENT_NAMESPACE = "touchable";

      kls.widgetName("Touchable");

      kls.configure({
        preventDefault: false,
        stopPropagation: false,
        gestures: []
      });

      function Touchable() {
        var gesture, options;
        Touchable.__super__.constructor.apply(this, arguments);
        options = this._options;
        this._gestures = (function() {
          var _i, _len, _ref, _results;
          _ref = options.gestures;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            gesture = _ref[_i];
            _results.push(new gesture(this, options));
          }
          return _results;
        }).call(this);
      }

      Touchable.prototype.onrender = function() {
        this.delegate();
        return Touchable.__super__.onrender.apply(this, arguments);
      };

      Touchable.prototype.ondestroy = function() {
        this.undelegate();
        return Touchable.__super__.ondestroy.apply(this, arguments);
      };

      Touchable.prototype.delegate = function() {
        var cls, touchCancelFn, touchEndFn, touchMoveFn, touchStartFn,
          _this = this;
        cls = this.constructor;
        touchMoveFn = function(e) {
          return _this._callGestures(kls.TOUCH_MOVE_EVENT, e);
        };
        touchEndFn = function(e) {
          doc.unbind(kls.eventName(events.TOUCH_MOVE_EVENT)).unbind(kls.eventName(events.TOUCH_END_EVENT)).unbind(kls.eventName(events.TOUCH_CANCEL_EVENT));
          return _this._callGestures(kls.TOUCH_END_EVENT, e);
        };
        touchCancelFn = function(e) {
          doc.unbind(kls.eventName(events.TOUCH_MOVE_EVENT)).unbind(kls.eventName(events.TOUCH_END_EVENT)).unbind(kls.eventName(events.TOUCH_CANCEL_EVENT));
          return _this._callGestures(kls.TOUCH_CANCEL_EVENT, e);
        };
        touchStartFn = function(e) {
          _this._callGestures(kls.TOUCH_START_EVENT, e);
          return doc.bind(kls.eventName(events.TOUCH_MOVE_EVENT), touchMoveFn).bind(kls.eventName(events.TOUCH_END_EVENT), touchEndFn).bind(kls.eventName(events.TOUCH_CANCEL_EVENT), touchCancelFn);
        };
        return this.element.bind(events.TOUCH_START_EVENT, touchStartFn);
      };

      Touchable.prototype.undelegate = function() {
        return this.element.unbind(events.TOUCH_START_EVENT);
      };

      Touchable.prototype._callGestures = function(name, event) {
        var gesture, method, _i, _len, _ref;
        _ref = this._gestures;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          gesture = _ref[_i];
          method = gesture["on" + name];
          if (method && method.call(gesture, event) === false) {
            break;
          }
        }
      };

      return Touchable;

    })(widgets.Widget);
    return {
      Touchable: Touchable
    };
  });

}).call(this);
