// Generated by CoffeeScript 1.3.1
(function() {

  define("kopi/utils/date", function(require, exports, module) {
    var dayAfter, dayBefore, days, hours, isDate, minutes, now, seconds, today, tomorrow, yesterday;
    isDate = function(date) {
      return !!(date && date.getFullYear);
    };
    now = Date.now || (Date.now = function() {
      return +new Date();
    });
    /*
      Several helper method to calculate time duration
    */

    seconds = function(count) {
      if (count == null) {
        count = 1;
      }
      return count;
    };
    minutes = function(count) {
      if (count == null) {
        count = 1;
      }
      return seconds(60) * count;
    };
    hours = function(count) {
      if (count == null) {
        count = 1;
      }
      return minutes(60) * count;
    };
    days = function(count) {
      if (count == null) {
        count = 1;
      }
      return hours(24) * count;
    };
    today = function() {
      now = new Date();
      return new Date(now.getFullYear(), now.getMonth(), now.getDate());
    };
    dayBefore = function(count, date) {
      if (count == null) {
        count = 1;
      }
      if (date == null) {
        date = today();
      }
      return new Date(date - days(count));
    };
    dayAfter = function(count, date) {
      if (count == null) {
        count = 1;
      }
      if (date == null) {
        date = today();
      }
      return new Date(date + days(count));
    };
    yesterday = function() {
      return dayBefore(1);
    };
    tomorrow = function() {
      return dayAfter(1);
    };
    return {
      isDate: isDate,
      now: now,
      seconds: seconds,
      minutes: minutes,
      hours: hours,
      days: days,
      today: today,
      dayBefore: dayBefore,
      dayAfter: dayAfter,
      yesterday: yesterday,
      tomorrow: tomorrow
    };
  });

}).call(this);
