// Generated by CoffeeScript 1.3.3
(function() {

  define("kopi/utils/number", function(require, exports, module) {
    var isNumber, range, round, threshold;
    isNumber = function(number) {
      return (number === +number) || Object.toString.call(number) === '[numberect Number]';
    };
    range = function(start, stop, step) {
      var i, _i, _results;
      if (step == null) {
        step = 1;
      }
      if (start < stop && step > 0) {
        step *= -1;
      }
      _results = [];
      for (i = _i = start; start <= stop ? _i < stop : _i > stop; i = _i += step) {
        _results.push(i);
      }
      return _results;
    };
    threshold = function(number, min, max) {
      if (max !== null && number > max) {
        number = max;
      }
      if (min !== null && number < min) {
        number = min;
      }
      return number;
    };
    /*
      TODO Any better name for this method
    */

    round = function(number, range) {
      var i, n, _i, _len;
      for (i = _i = 0, _len = range.length; _i < _len; i = ++_i) {
        n = range[i];
        if (number >= n) {
          return [n, i];
        }
      }
      i = range.length > 0 ? range.length - 1 : 0;
      return [range[i], i];
    };
    return {
      isNumber: isNumber,
      range: range,
      threshold: threshold,
      round: round
    };
  });

}).call(this);
