// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  define("kopi/db/adapters/ios", function(require, exports, module) {
    var IOSSQLAdapter, sql;
    sql = require("kopi/db/adapters/sql");
    IOSSQLAdapter = (function(_super) {

      __extends(IOSSQLAdapter, _super);

      IOSSQLAdapter.name = 'IOSSQLAdapter';

      function IOSSQLAdapter() {
        return IOSSQLAdapter.__super__.constructor.apply(this, arguments);
      }

      return IOSSQLAdapter;

    })(sql.SQLAdapter);
    return {
      IOSSQLAdapter: IOSSQLAdapter
    };
  });

}).call(this);
